theme = 'ananke' 
baseURL = 'http://www.dfcubidesc.com/'
languageCode = 'en-us'
title = 'dfcubidesc'

DefaultContentLanguage = "en"
SectionPagesMenu = "main"
publishDir = "docs"
pagination.pagerSize = 10  # This would limit to 4 posts per page



[params]
  text_color = ""
  author = ""
  favicon = ""
  site_logo = ""
  description = "The last theme you'll ever need. Maybe."
  # choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  recent_posts_number = 8
  [social]
    linkedin = "https://www.linkedin.com/in/dfernandocubicesc/"
    github = "https://github.com/DanielFCubides"
    # other social media


[outputs]
  home = ["HTML"]

